#!/usr/bin/env sh

set -e

function usage() {
    echo "PROBE record [-h|--help] [-o|--output OUTPUT] [-g|--gdb] [-v|--debug] [-m|--make] CMD ARGS..."
    echo ""
    echo "Executes CMD ARGS... using libprobe"
    echo ""
    echo "    -h|--help: Show this message and quit"
    echo "    -o|--output OUTPUT: write output to the file OUTPUT"
    echo "    -g|--gdb: Run CMD with libprobe in GDB"
    echo "    -d|--debug: Use debug-and-verbose version of libprobe"
    echo "    -m|--make: make libprobe before executing (assuming dev repository)"
    echo ""
}

output=probe_log.tar.gz
gdb=
make=
debug=

while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            usage
            exit 1
            ;;
        -o|--output)
            shift
            output=$1
            shift
            ;;
        -g|--gdb)
            gdb=1
            shift # past argument
            ;;
        -d|--debug)
            debug=1
            shift # past argument
            ;;
        -m|--make)
            export make=1
            shift # past argument
            ;;
        -*|--*)
            echo "Unknown option $1"
            usage
            exit 1
            ;;
        *)
            break
            ;;
    esac
done

if [ "$#" = 0 ]; then
    echo "No CMD supplied"
    usage
    exit 1
fi

if [ -n "${make}" ]; then
    make --directory libprobe all
fi

libprobe_root="$(realpath -- "$(dirname "$0")/libprobe/build")"

if [ -n "${debug}" -o -n "${gdb}" ]; then
    libprobe="${libprobe_root}/libprobe-dbg.so"
    echo "Running '${@}' in libprobe"
else
    libprobe="${libprobe_root}/libprobe.so"
    echo "When libprobe opt is ready, that command would execute it."
    echo "However, I need more time to make sure the error-handling code works correctly in opt."
    echo "Please rerun with -d|--debug."
    exit 1
fi

if [ ! -f "${libprobe}" ]; then
    echo "${libprobe} does not exist"
    exit 1
fi

export PROBE_DIR="$(mktemp --directory --quiet /tmp/prov-log-XXXXXXXXXX)"

if [ -n "${gdb}" ]; then
    gdb --args env "LD_PRELOAD=${libprobe}" "${@}"
else
    set +e
    env LD_PRELOAD=$libprobe "${@}"
    status=$?
    if [ -z "${debug}" ]; then
        tar --compress --gzip --file "${output}" "${PROBE_DIR}"
    fi
    exit $status
fi
