import os


class Dot:
    def set(self, key: str, value: str) -> None: ...
    def add_node(self, node: str) -> str: ...
    def get_node(self, node: str) -> str: ...
    def add_subgraph(self, subgraph: Subgraph) -> None: ...
    def write_raw(self, f: os.PathLike[str]) -> None: ...
    def write_png(self, f: os.PathLike[str]) -> None: ...

class Subgraph(Dot):
    def __init__(self, name: str, **value: str): ...
