#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */


    #include <stdint.h>    // for uint32_t
    #include <stdbool.h>   // for bool
    #include <sys/types.h> // for suseconds_t

    #define LD_PRELOAD_VAR "LD_PRELOAD"
    #define PROBE_DIR_VAR "PROBE_DIR"
    #define PROBE_COPY_FILES_VAR "PROBE_COPY_FILES"
    #define PIDS_SUBDIR "pids"
    #define CONTEXT_SUBDIR "context"
    #define INODES_SUBDIR "inodes"
    #define PROCESS_TREE_CONTEXT_FILE "process_tree_context"
    #define DATA_SUBDIR "data"
    #define OPS_SUBDIR "ops"

    
typedef char const * _Nonnull ByteString;

typedef char const * _Nullable Option_ByteString;

typedef char const * _Nullable const * _Nonnull StringArray;
/*generate*/
    

#define PROBE_PATH_MAX 4096

enum CopyFiles {
    CopyFiles_None,
    CopyFiles_Lazily,
    CopyFiles_Eagerly,
};
typedef uint8_t CopyFiles;

enum FileType {
    FileType_Dir,
    FileType_Fifo,
    FileType_Pipe,
};
typedef uint8_t FileType;

enum TaskType {
    TaskType_Pid,
    TaskType_Tid,
    TaskType_IsoCThread,
    TaskType_Pthread,
};
typedef uint8_t TaskType;



struct FixedPath {
    char bytes[PROBE_PATH_MAX];
    uintptr_t len;
};

struct ProcessTreeContext {
    struct FixedPath libprobe_path;
    CopyFiles copy_files;
    uint32_t parent_of_root;
};

struct ProcessContext {
    uint16_t epoch_no;
    struct FixedPath process_tree_path;
    bool enable_recording;
};

struct StatxTimestamp {
    long long tv_sec;
    unsigned int tv_nsec;
    unsigned int __padding;
};

struct Path {
    int32_t dirfd;
    Option_ByteString path;
    uint32_t device_major;
    uint32_t device_minor;
    ino_t inode;
    uint16_t mode;
    struct StatxTimestamp mtime;
    struct StatxTimestamp ctime;
    uint64_t size;
    bool stat_valid;
};

struct AccessOp {
    struct Path path;
    int mode;
    int flags;
    int ferrno;
};

struct ChdirOp {
    struct Path path;
    int ferrno;
};

struct CloneOp {
    int flags;
    bool run_pthread_atfork_handlers;
    TaskType task_type;
    int64_t task_id;
    int ferrno;
};

struct CloseOp {
    int32_t fd;
    int ferrno;
    struct Path path;
};

struct DupOp {
    struct Path path;
    int old;
    int new_;
    int flags;
    int ferrno;
};

struct ExecOp {
    struct Path path;
    int ferrno;
    StringArray argv;
    StringArray env;
};

struct ExitProcessOp {
    int status;
};

struct ExitThreadOp {
    int status;
};

struct HardLinkOp {
    struct Path old;
    struct Path new_;
    int ferrno;
};

struct InitExecEpochOp {
    pid_t parent_pid;
    pid_t pid;
    uint32_t epoch;
    struct Path cwd;
    struct Path exe;
    StringArray argv;
    StringArray env;
    struct Path std_in;
    struct Path std_out;
    struct Path std_err;
};

struct InitThreadOp {
    pid_t tid;
};

struct MkFileOp {
    struct Path path;
    FileType file_type;
    int flags;
    mode_t mode;
    int ferrno;
};

struct OpenOp {
    struct Path path;
    int flags;
    mode_t mode;
    int32_t fd;
    int ferrno;
};

struct ReadLinkOp {
    struct Path linkpath;
    ByteString referent;
    bool truncation;
    bool recursive_dereference;
    int ferrno;
};

struct ReaddirOp {
    struct Path dir;
    Option_ByteString child;
    bool all_children;
    int ferrno;
};

struct RenameOp {
    struct Path src;
    struct Path dst;
    int ferrno;
};

struct SpawnOp {
    struct ExecOp exec;
    pid_t child_pid;
    int ferrno;
};

struct StatResult {
    uint32_t mask;
    uint32_t nlink;
    uint32_t uid;
    uint32_t gid;
    uint16_t mode;
    uint16_t __padding0;
    uint64_t ino;
    uint64_t size;
    uint64_t blocks;
    uint32_t blksize;
    struct StatxTimestamp atime;
    struct StatxTimestamp btime;
    struct StatxTimestamp ctime;
    struct StatxTimestamp mtime;
    uint32_t dev_major;
    uint32_t dev_minor;
    uint64_t __padding1[12];
};

struct StatOp {
    struct Path path;
    int flags;
    int ferrno;
    struct StatResult stat_result;
};

struct SymbolicLinkOp {
    ByteString old;
    struct Path new_;
    int ferrno;
};

struct UnlinkOp {
    struct Path path;
    int unlink_type;
    int ferrno;
};

struct Ownership {
    uid_t uid;
    gid_t gid;
};

typedef int64_t TimeT;

typedef int64_t SusecondsT;

struct TimeVal {
    TimeT tv_sec;
    SusecondsT tv_usec;
};

struct Times {
    bool is_null;
    struct TimeVal atime;
    struct TimeVal mtime;
};

enum MetadataValue_Tag {
    MetadataValue_Mode,
    MetadataValue_Ownership,
    MetadataValue_Times,
};
typedef uint8_t MetadataValue_Tag;

union MetadataValue {
    MetadataValue_Tag tag;
    struct {
        MetadataValue_Tag mode_tag;
        mode_t mode;
    };
    struct {
        MetadataValue_Tag ownership_tag;
        struct Ownership ownership;
    };
    struct {
        MetadataValue_Tag times_tag;
        struct Times times;
    };
};

struct UpdateMetadataOp {
    struct Path path;
    int flags;
    union MetadataValue value;
    int ferrno;
};

struct Rusage {
    struct TimeVal ru_utime;
    struct TimeVal ru_stime;
    long ru_maxrss;
    long ru_ixrss;
    long ru_idrss;
    long ru_isrss;
    long ru_minflt;
    long ru_majflt;
    long ru_nswap;
    long ru_inblock;
    long ru_oublock;
    long ru_msgsnd;
    long ru_msgrcv;
    long ru_nsignals;
    long ru_nvcsw;
    long ru_nivcsw;
};

struct WaitOp {
    TaskType task_type;
    int64_t task_id;
    int options;
    int status;
    bool cancelled;
    struct Rusage usage;
    int ferrno;
};

enum OpData_Tag {
    OpData_Access,
    OpData_Chdir,
    OpData_Clone,
    OpData_Close,
    OpData_Dup,
    OpData_Exec,
    OpData_ExitProcess,
    OpData_ExitThread,
    OpData_HardLink,
    OpData_InitExecEpoch,
    OpData_InitThread,
    OpData_MkFile,
    OpData_Open,
    OpData_ReadLink,
    OpData_Readdir,
    OpData_Rename,
    OpData_Spawn,
    OpData_Stat,
    OpData_SymbolicLink,
    OpData_Unlink,
    OpData_UpdateMetadata,
    OpData_Wait,
    /**
     * Must be last for serialization purposes
     */
    OpData_Sentinel,
};
typedef uint8_t OpData_Tag;

union OpData {
    OpData_Tag tag;
    struct {
        OpData_Tag access_tag;
        struct AccessOp access;
    };
    struct {
        OpData_Tag chdir_tag;
        struct ChdirOp chdir;
    };
    struct {
        OpData_Tag clone_tag;
        struct CloneOp clone;
    };
    struct {
        OpData_Tag close_tag;
        struct CloseOp close;
    };
    struct {
        OpData_Tag dup_tag;
        struct DupOp dup;
    };
    struct {
        OpData_Tag exec_tag;
        struct ExecOp exec;
    };
    struct {
        OpData_Tag exit_process_tag;
        struct ExitProcessOp exit_process;
    };
    struct {
        OpData_Tag exit_thread_tag;
        struct ExitThreadOp exit_thread;
    };
    struct {
        OpData_Tag hard_link_tag;
        struct HardLinkOp hard_link;
    };
    struct {
        OpData_Tag init_exec_epoch_tag;
        struct InitExecEpochOp init_exec_epoch;
    };
    struct {
        OpData_Tag init_thread_tag;
        struct InitThreadOp init_thread;
    };
    struct {
        OpData_Tag mk_file_tag;
        struct MkFileOp mk_file;
    };
    struct {
        OpData_Tag open_tag;
        struct OpenOp open;
    };
    struct {
        OpData_Tag read_link_tag;
        struct ReadLinkOp read_link;
    };
    struct {
        OpData_Tag readdir_tag;
        struct ReaddirOp readdir;
    };
    struct {
        OpData_Tag rename_tag;
        struct RenameOp rename;
    };
    struct {
        OpData_Tag spawn_tag;
        struct SpawnOp spawn;
    };
    struct {
        OpData_Tag stat_tag;
        struct StatOp stat;
    };
    struct {
        OpData_Tag symbolic_link_tag;
        struct SymbolicLinkOp symbolic_link;
    };
    struct {
        OpData_Tag unlink_tag;
        struct UnlinkOp unlink;
    };
    struct {
        OpData_Tag update_metadata_tag;
        struct UpdateMetadataOp update_metadata;
    };
    struct {
        OpData_Tag wait_tag;
        struct WaitOp wait;
    };
};

struct Op {
    union OpData data;
    uint16_t pthread_id;
    uint64_t iso_c_thread_id;
};

struct ArenaHeader {
    uintptr_t instantiation;
    uintptr_t base_address;
    uintptr_t capacity;
    uintptr_t used;
};
