use eyre::{Result, WrapErr};

fn main() {
    let _ = inner().map_err(|err| eprintln!("Not writing files: {err:?}"));
}

fn inner() -> Result<()> {
    let crate_dir = std::env::var("CARGO_MANIFEST_DIR").wrap_err("CARGO_MANIFEST_DIR")?;
    let out_file = std::env::var("CBINDGEN_OUTFILE").wrap_err("CBINDGEN_OUTFILE")?;
    println!("To {out_file}");

    println!("cargo:rerun-if-changed=src/ops.rs");

    cbindgen::Builder::new()
        .with_crate(&crate_dir)
        .with_language(cbindgen::Language::C)
        .with_pragma_once(true)
        .with_autogen_warning(
            "/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */",
        )
        .with_after_include(
            "
    #include <stdint.h>    // for uint32_t
    #include <stdbool.h>   // for bool
    #include <sys/types.h> // for suseconds_t

    #define LD_PRELOAD_VAR \"LD_PRELOAD\"
    #define PROBE_DIR_VAR \"PROBE_DIR\"
    #define PROBE_COPY_FILES_VAR \"PROBE_COPY_FILES\"
    #define PIDS_SUBDIR \"pids\"
    #define CONTEXT_SUBDIR \"context\"
    #define INODES_SUBDIR \"inodes\"
    #define PROCESS_TREE_CONTEXT_FILE \"process_tree_context\"
    #define DATA_SUBDIR \"data\"
    #define OPS_SUBDIR \"ops\"

    /*generate*/
    ",
        )
        .with_no_includes()
        .with_tab_width(4)
        .with_style(cbindgen::Style::Tag)
        .include_item("ProcessTreeContext")
        .include_item("ProcessContext")
        .include_item("Op")
        .include_item("ArenaHeader")
        .generate()
        .wrap_err("Generating bindings")?
        .write_to_file(&out_file);

    let source = std::fs::read_to_string(&out_file)?;
    let source = replace_with_typedef(source, "ByteString", "char const * _Nonnull");
    let source = replace_with_typedef(source, "Option_ByteString", "char const * _Nullable");
    let source = replace_with_typedef(
        source,
        "StringArray",
        "char const * _Nullable const * _Nonnull",
    );
    std::fs::write(&out_file, source).wrap_err("writing C headers")?;

    Ok(())
}

fn replace_with_typedef(c_source: String, struct_name: &str, typedef: &str) -> String {
    let new_source = c_source
        .replace(&format!("struct {struct_name};"), "")
        .replace(&format!("struct {struct_name}"), struct_name)
        .replace(
            "/*generate*/",
            &format!("\ntypedef {typedef} {struct_name};\n/*generate*/"),
        );
    new_source
}
