swappiness: 60
perf_event_paranoid: 1
cpus:
  0:
    cpufreq_scaling_governor: powersave
    online: null
  1:
    cpufreq_scaling_governor: powersave
    online: 1
  2:
    cpufreq_scaling_governor: powersave
    online: 1
  3:
    cpufreq_scaling_governor: powersave
    online: 1
  4:
    cpufreq_scaling_governor: powersave
    online: 1
  5:
    cpufreq_scaling_governor: powersave
    online: 1
  6:
    cpufreq_scaling_governor: powersave
    online: 1
  7:
    cpufreq_scaling_governor: powersave
    online: 1
