#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

use serde::{Deserialize, Serialize};

// Bindings are generated by `../build.sh`
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
